1  TEXT : HOME : NORMAL : VTAB (5): HTAB (9): PRINT "WELCOME,  FOOLISH MORTAL": VTAB (7): HTAB (14): PRINT "INTO THE WORLD": VTAB (9): HTAB (16): INVERSE : PRINT "AKALABETH!": NORMAL 
2  VTAB (11): HTAB (7): PRINT "HEREIN THOU SHALT FIND GRAND": VTAB (13): HTAB (16): INVERSE : PRINT "ADVENTURE!": NORMAL 
3  VTAB (16): PRINT "        CREATED BY  LORD BRITISH": PRINT : PRINT "(C) 1980 BY CALIFORNIA PACIFIC COMPUTER"
4  VTAB (21): HTAB (10): PRINT "INSTRUCTIONS (Y/N) ?";: GET Q$: PRINT Q$: VTAB (23): HTAB (8): PRINT "(PRESS SPACE TO CONTINUE) ";: GET R$: PRINT : IF Q$ = "N" THEN 8998
5  PRINT "BLOAD AKA4"
6  POKE 254,32: POKE 255,32: POKE 32840,169: POKE 32841,0: CALL 32768: POKE 32840,177: POKE 32841,8
7  PRINT "BLOADAKA2,A$2000": POKE  - 16302,0: POKE  - 16297,0: POKE  - 16300,0: POKE  - 16304,0
8  PRINT "BLOADAKA5,A$4000"
9  CALL 32768
10  PRINT "BLOADAKA3,A$4000"
11  POKE 32769,39: POKE 32888,136: POKE 32890,255: CALL 32768: POKE 32769,0: POKE 32888,200: POKE 32890,40
12  FOR O7 = 1 TO 4000: NEXT O7
13  POKE 32840,169: POKE 32841,0: CALL 32768: POKE 32840,177: POKE 32641,8
14  FOR O7 = 1 TO 500: NEXT O7
8000  HOME : TEXT : HOME 
8010  PRINT : PRINT : PRINT "     MANY, MANY, MANY YEARS AGO THE": PRINT "DARK LORD MONDAIN, ARCHFOE OF BRITISH,": PRINT "TRAVERSED THE LANDS OF AKALABETH": PRINT "SPREADING EVIL AND DEATH AS HE PASSED."
8020  PRINT "BY THE TIME MONDAIN WAS DRIVEN FROM THE": PRINT "LAND BY BRITISH, BEARER OF THE WHITE": PRINT "LIGHT, HE HAD DONE MUCH DAMAGE UNTO"
8030  PRINT "THE LANDS.": PRINT : PRINT "'TIS THY DUTY TO HELP RID AKALABETH OF": PRINT "THE FOUL BEASTS WHICH INFEST IT,": PRINT "WHILE TRYING TO STAY ALIVE!!!": PRINT : PRINT : PRINT "       (PRESS SPACE TO CONTINUE)";: GET Q$
8100  HOME : VTAB (2): HTAB (12): PRINT "THE PLAYER STAT'S:"
8105  PRINT : PRINT : PRINT : PRINT "HIT POINTS- AMOUNT OF DAMAGE A PLAYER": HTAB (13): PRINT "CAN ABSORB BEFORE DEATH"
8110  PRINT : PRINT "STRENGTH--- RELATED TO DAMAGE INFLICTED": HTAB (13): PRINT "BY PLAYER AGAINST MONSTERS."
8120  PRINT : PRINT "DEXTERITY-- RELATED TO THE PROBABILITY": HTAB (13): PRINT "OF A PLAYER HITTING A MONST."
8130  PRINT "STAMINA---- RELATED TO PLAYER DEFENSE": HTAB (13): PRINT "AGAINST MONSTERS"
8140  PRINT : PRINT "WISDOM----- THIS ATTRIBUTE IS USED": HTAB (13): PRINT "IN SPECIAL (QUEST!) ROUTINES"
8150  PRINT "GOLD------- MONEY!! CASH!! ASSETS!!"
8160  PRINT : PRINT : HTAB (8): PRINT "(PRESS SPACE TO CONTINUE)";: GET Q$
8200  HOME : PRINT : PRINT "       THE TOWNS AND BUYING ITEMS:"
8210  PRINT : PRINT : PRINT "     TO BUY ANY ITEM ONE NEED ONLY": PRINT "TYPE THE FIRST LETTER OF THE ITEM"
8220  PRINT "WANTED. THE COST OF THE RESPECTIVE": PRINT "ITEMS IS DISPLAYED WHILE IN THE TOWN."
8230  PRINT "THE GAME IS STARTED IN A TOWN SOMEWHERE": PRINT "ON THE 20X20 MAP."
8240  PRINT : PRINT : HTAB (12): PRINT "FIGHTERS AND MAGI"
8250  PRINT : PRINT "     THE DISADVANTAGE OF BEING A": PRINT "FIGHTER IS THE LACK OF THE ABILITY TO": PRINT "CONTROL THE MAGIC AMULET, WHEREAS MAGI": PRINT "CAN NOT USE RAPIERS OR BOWS."
8270  PRINT : PRINT : HTAB (8): PRINT "(PRESS SPACE TO CONTINUE)";: GET Q$
8300  HOME : PRINT : PRINT : HTAB (16): PRINT "MOVEMENT:"
8310  PRINT : PRINT : PRINT "-KEY-";: HTAB (10): PRINT "OUTDOORS";: HTAB (24): PRINT "DUNGEON"
8320  PRINT : PRINT "  CR     MOVE NORTH    MOVE FORWARD": PRINT "  <=     MOVE WEST     TURN LEFT   ": PRINT "  =>     MOVE EAST     TURN RIGHT"
8330  PRINT "  /      MOVE SOUTH    TURN AROUND": PRINT "  S      STATISTICS    STATISTICS": PRINT "  A      N/A           ATTACK    ": PRINT "  P      PAUSE ON/OFF  PAUSE ON/OFF"
8335  PRINT "  X      GO INTO TOWN  CLIMB LADDER": PRINT "  X      GO CASTLE     GO HOLE     ": PRINT "SPACE    PASS          PASS        "
8350  PRINT : PRINT : HTAB (8): PRINT "(PRESS SPACE TO CONTINUE)";: GET Q$
8400  HOME : VTAB (5): PRINT "     THOU DOEST NOW KNOW THE BASICS OF": PRINT : PRINT "THE GAME, EXPERIMENT WITH THE COMMANDS."
8410  PRINT : PRINT "THERE IS MUCH THAT IS LEFT UNSAID FOR": PRINT : PRINT "THEE TO DISCOVER IN THE FUTURE..."
8420  PRINT : PRINT : PRINT "     GO NOW UNTO THE WORLD AND SEEK": PRINT : PRINT "ADVENTURE WHERE THOU MIGHT!!!"
8430  PRINT : PRINT : PRINT "P.S.-SEARCH OUT THE CASTLE OF": PRINT "LORD BRITISH, USE THE -X- KEY TO GO IN!"
8450  PRINT : PRINT : HTAB (8): PRINT "(PRESS SPACE TO CONTINUE)";: GET Q$
8997  PRINT 
8998  POKE 33,1: POKE 34,23
8999  PRINT "RUN AKA1"
0 
